language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
## cache是缓存的，不需要每次都安装依赖，缓存下来了,设置环境变量
env:
  - CI=true
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: $GITHUB_TOKEN
  on:
    branch: master